application: eco-muse-597
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /app
  static_dir: /app

- url: /.*
  script: console.application
